on:
  push:
    tags: '*'

  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set release name
        run: sed -i "s/^\s+version '.*'/version '${{ github.event.inputs.version }}'/" build.gradle && cat build.gradle
        if: ${{ github.event.inputs.version }}
      - name: Build the project
        run: ./gradlew build --stacktrace
      - name: Publish package to Github
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}